module.exports = {
	UserInfo_service: require("./userInfo_services"),
	Users_service: require("./users_services"),
	Loan_service: require("./loan_services"),
	Employment_service: require("./employment_services"),
	Company_service: require("./company_services"),
	Admin_service: require("./Admin_services"),
	Id_analyzer: require("./idAnaliser"),
	Bank_service: require("./bank_services"),
	PanCardAnalyzer: require("./PancardAnaliser_services"),
	EMI_calculator_services: require("./emiCalculator_services"),
	JobAssignees_service: require("./JobAssignees_services"),
	GeneratePdf_service: require("./generatePdf_services"),
	Log_service: require("./Log_services"),
};
