module.exports = {
  UserInfo_repository: require("./user repositories/userInfo_repository"),
  Users_repository: require("./user repositories/users_repository"),
  Loan_repository: require("./user repositories/loan_repositry"),
  Bank_repository: require("./user repositories/bank_repository"),
  Employment_repository: require("./user repositories/employment_repository"),
  Company_repository: require("./common repositories/company_repositry"),
  Admin_repository: require("./admin repositories/admin_repository"),
  EMI_calculator: require("./common repositories/emiCalculator_repository"),
  JobAssignee_Repo: require("./admin repositories/jobAssignees_repository"),
  Log_repository: require("./admin repositories/log_repository"),
  Logcondition_repository: require("./admin repositories/logCondition_repository"),
  Generate_Pdf: require("./common repositories/pdfGenerator_repository"),
  borrowerTxn_Repo: require("./user repositories/borrower_txn_repository"),
  poolTxn_Repo: require("./admin repositories/pool_txn_repository"),
  BorrowerWallet: require("./user repositories/borrower_wallet_repository"),
  Pool_repository: require("./admin repositories/pool_repository"),
};
